#!/bin/sh

usage()
{
printf '%s\n' "This is latex2sixel V 1.0.2 :: (posix, TeX Live)

Usage: $0 [OPTION]... TEXSTRING
Options are chosen to be similar to dvips' options where possible:

  -D #         Output resolution
  -O c         Image offset
  -T c         Image size (also accepts '-T bbox' and '-T tight')

  -bg s        Background color (TeX-style color or 'Transparent')
  -fg s        Foreground color (TeX-style color)

  -h | --help  Help

  # = number   s = string
  c = comma-separated dimension pair (e.g., 3.2in,-32.1cm)

  TEXSTRING is a LaTeX expression betweeen apostrophes (not quotes).
  Examples: '\$\alpha\$' | '\LaTeX' | 'This is math: \$x+y\$'.

Required applications: latex, dvipng, img2sixel.
Terminals supporting sixel graphics: xterm -ti vt340, mintty, mlterm and more."
}

[ $# -eq 0 ] && { usage;exit; };
[ "$1" = -h ] || [ "$1" = --help ] && { usage;exit; };

#
# config (default)
#
pt=11pt
fg=Green
bg=Black
D=150  #120
T=bbox  #bbox,tight ...
O=-1.0cm,-2.0cm
img="$(mktemp latex2sixel_XXXXXX)"
jobname="$(mktemp latex2sixel_XXXXXX)"

trap 'rm "$img" "$jobname" "$jobname.aux" "$jobname.dvi" "$jobname.log"' EXIT INT

#
# option parsing
#
while [ $# -gt 1 ]; do
arg="$1"

case $arg in
    -D|--resolution)
    D="$2"
    shift # past argument
    ;;
    -O|--offset)
    O="$2"
    shift # past argument
    ;;
    -T|--size)
    T="$2"
    shift # past argument
    ;;
    -fg|--forecolor)
    fg="$2"
    ;;
    -bg|--backcolor)
    bg="$2"
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done


#
# TeX
#

texsrc="$1"

TEX="\documentclass[$pt]{article}
\usepackage{amsmath,amssymb}
\usepackage{breqn}
\pagestyle{empty}
\begin{document}
$texsrc
\end{document}"
TEX="$(printf '%s\n' "$TEX" | tr '\n' ' ')"

LATEX="latex -jobname=$jobname -interaction=nonstopmode"
DVIPNG="dvipng -T $T -D $D -O $O -fg $fg -bg $bg -q -o $img"

printf '%s\n' "$TEX" | $LATEX > /dev/null 2>&1
$DVIPNG "$jobname.dvi" > /dev/null 2>&1
img2sixel "$img"
