#!/bin/bash


function usage()
{
cat <<ENDUSAGE

This is latex2sixel V 1.0.2 (Mon Apr 11 15:59:19 CEST 2022)

Usage: $0 [OPTION]... TEXSTRING
Options are chosen to be similar to dvips' options where possible:

  -D #         Output resolution
  -O c         Image offset
  -T c         Image size (also accepts '-T bbox' and '-T tight')

  -bg s        Background color (TeX-style color or 'Transparent')
  -fg s        Foreground color (TeX-style color)

  -h | --help  Help

  # = number   s = string
  c = comma-separated dimension pair (e.g., 3.2in,-32.1cm)

  TEXSTRING is a LaTeX expression betweeen apostrophes (not quotes).
  Examples: '\$\alpha\$' | '\LaTeX' | 'This is math: \$x+y\$'.

Required applications: latex, dvipng, img2sixel.
Terminals supporting sixel graphics: xterm -ti vt340, mintty, mlterm.
More info @  https://github.com/saitoha/libsixel
ENDUSAGE
}

if ! tty -s; then
    set -- "$@" "$(</dev/stdin)"
fi

[[ $# == 0 ]]        && { usage;exit; };

#
# config (default)
#
pt=11pt
fg=Green
bg=Black
D=150  #120
T=bbox  #bbox,tight ...
O=-1.0cm,-2.0cm
tmpdir=$(mktemp --tmpdir -d l2s.XXXXXX)
key=$tmpdir/l2s
img=$key-$(tr -dc '[A-Za-z]' <<<"$1" | cut -c-70).png

trap cleanup EXIT
function cleanup() {
    # CAUTION -- removing files
    # You may comment the line below if unsure ;)
    rm -r "$tmpdir"
}

trap die ERR
function die() {
    echo -n "latex2sixel: Dying at line "
    caller
    for arg; do echo; echo "$arg"; done
    kill 0			# Exit even though we're in a subshell
}

#
# option parsing
#
TEMP=$(getopt -a -n 'latex2sixel' -o 'D:O:T:h' \
       --long 'resolution:,offset:,size:,fg:,forecolor:,bg:,backcolor,help' \
       -- "$@")
if [ $? -ne 0 ]; then
    usage; exit 1
fi
eval set -- "$TEMP"		# Set Bash argv in "$@"
unset TEMP

while true; do
    case "$1" in
	-h|--help) usage; exit
	    ;;
	-D|--resolution)
	    D="$2"
	    shift 2 # past argument
	    continue
	    ;;
	-O|--offset)
	    O="$2"
	    shift 2 # past argument
	    continue
	    ;;
	-T|--size)
	    T="$2"
	    shift 2 # past argument
	    continue
	    ;;
	--fg|--forecolor)
	    fg="$2"
	    shift 2 # past argument
	    continue
	    ;;
	--bg|--backcolor)
	    bg="$2"
	    shift 2 # past argument
	    continue
	    ;;
	--) shift; break
	    ;;
	*)
            echo 'Internal Error' >&2
	    exit 1
	    ;;
    esac
done


# TeX template 

TEX=$(cat <<EOF
\documentclass[$pt]{article}
\usepackage{amsmath,amssymb}
\usepackage{breqn}
\pagestyle{empty}
\begin{document}
 $@
\end{document}
EOF
)


LATEX="latex -jobname=$key -halt-on-error -output-directory $tmpdir"
DVIPNG="dvipng -T $T -D $D -O $O -fg $fg -bg $bg -q -o $img"


$LATEX <<<"$TEX" > /dev/null ||
    die "$(sed -n '/^Here is how much of TeX/,$d;/^!/,$ p' $key.log)"
$DVIPNG $key.dvi  > /dev/null
img2sixel $img

# Temp files are automatically removed by cleanup() at exit.
